version: '3.8'
services:
  cliente-service:
    build: ./cliente
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:clientes
    
  produto-service:
    build: ./produto
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:produtos
    
  pedido-service:
    build: ./pedido
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:pedidos
